### ISSUE TITLE
Error when generating documentation for the minimap package

### ISSUE THREAD

**Issue by abe33** [lee-dohm/endokken#20]
I'm not sure what trigger this error as I was just trying your package for the first time. Maybe it's something related to the various mixins used in the package?

```
/Users/cedric/.nvm/v0.10.21/lib/node_modules/endokken/node_modules/donna/src/metadata.coffee:363
        moduleName = exp.args[0].base.value;
                                     ^
TypeError: Cannot read property 'value' of undefined
  at Metadata.module.exports.Metadata.evalCall (/Users/cedric/.nvm/v0.10.21/lib/node_modules/endokken/node_modules/donna/src/metadata.coffee:282:36)
  at Metadata.module.exports.Metadata.eval (/Users/cedric/.nvm/v0.10.21/lib/node_modules/endokken/node_modules/donna/src/metadata.coffee:23:5)
  at Metadata.module.exports.Metadata.visitAssign (/Users/cedric/.nvm/v0.10.21/lib/node_modules/endokken/node_modules/donna/src/metadata.coffee:36:13)
  at Metadata.module.exports.Metadata.visit (/Users/cedric/.nvm/v0.10.21/lib/node_modules/endokken/node_modules/donna/src/metadata.coffee:21:5)
  at /Users/cedric/.nvm/v0.10.21/lib/node_modules/endokken/node_modules/donna/src/metadata.coffee:18:42
  at /Users/cedric/.nvm/v0.10.21/lib/node_modules/endokken/node_modules/coffee-script/lib/coffee-script/nodes.js:210:17
  at Block.exports.Base.Base.eachChild (/Users/cedric/.nvm/v0.10.21/lib/node_modules/endokken/node_modules/coffee-script/lib/coffee-script/nodes.js:198:17)
  at Block.exports.Base.Base.traverseChildren (/Users/cedric/.nvm/v0.10.21/lib/node_modules/endokken/node_modules/coffee-script/lib/coffee-script/nodes.js:208:19)
  at Metadata.module.exports.Metadata.generate (/Users/cedric/.nvm/v0.10.21/lib/node_modules/endokken/node_modules/donna/src/metadata.coffee:18:11)
  at generateMetadataSlug (/Users/cedric/.nvm/v0.10.21/lib/node_modules/endokken/node_modules/donna/src/donna.coffee:121:14)
  at Object.generateMetadata (/Users/cedric/.nvm/v0.10.21/lib/node_modules/endokken/node_modules/donna/src/donna.coffee:75:24)
  at Cli.generateMetadata (/Users/cedric/.nvm/v0.10.21/lib/node_modules/endokken/src/cli.coffee:79:23)
  at Cli.run (/Users/cedric/.nvm/v0.10.21/lib/node_modules/endokken/src/cli.coffee:30:6)
  at Object.<anonymous> (/Users/cedric/.nvm/v0.10.21/lib/node_modules/endokken/bin/endokken:7:5)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:901:3
```

Configuration: 
- OSX 10.10.2
- Node 0.10.21

**Comment by lee-dohm** [comment]
Thanks, I'll take a look!

**Comment by lee-dohm** [comment]
It's choking on:

```coffee
Decoration = require path.join(atom.config.resourcePath, 'src', 'decoration')
```

I tried changing it to `"#{atom.config.resourcePath}/src/decoration` and that also didn't work. I'm going to see about making a change to [donna](https://github.com/atom/donna) to more gracefully handle errors here.

**Comment by lee-dohm** [comment]
If you comment out that one line, it appears that everything generates fine. Well, some of the formatting is wonky, but that's because you're not strictly following the formatting of function parameters ... but the pages generate.

**Comment by abe33** [comment]
Ok, I'll take a look at that after work :).
